{
    // let a = 1; 
    // let b = 1;
    // let c = 1;
    // let d = 1;
    // let e = 1; 
    // let f = 1;
    // let g = 1;
    // let h = 1;
    // let j = 1; 
    // let k = 1;
    // let l = 1;
    // let m = 1;
    // let n = 1; 
    // let o = 1;
    // let p = 1;
    // let q = 1;
    // let r = 1; 
    // let s = 1;
    // let t = 1;
    // let u = 1;
    // 
    // let z = a + b + c + d + e + f + g  + h + j + k + l + m + n + o + p + q + r + s + t + u;

    let a = 1;
    
    if (a) { a += a - 1; }
    else { a -= a * 2; }

    // 
    // a(1);
}