namespace TempleLang.Lexer.Abstractions
{
    /// <summary>
    /// Represents a stream of tokens generated by lexing a file
    /// </summary>
    /// <typeparam name="TTokenType">The TokenType implementation to use for the tokens</typeparam>
    public interface ITokenStream<out TTokenType> : IReadonlyTokenStream<TTokenType>
    {
        /// <summary>
        /// Gets the next token from the stream, and steps to the next one
        /// </summary>
        /// <returns>The next token from the stream</returns>
        IToken<TTokenType> Read();

        /// <summary>
        /// Steps to the next token
        /// </summary>
        void Step();
    }
}